[window]
dimensions = {columns = 140, lines = 70}

[font]
normal = {family = "Monoid", style = "Regular"}
size = 12.25

[colors]
[colors.primary]
background = "#000000"

[keyboard]
bindings = [
	{key = "F11", action = "ToggleFullscreen"},
	{key = "F12", action = "CreateNewWindow"}
]
